"use client";

import React, { useState, useEffect, useRef } from "react";
import { 
  X, Save, PlusCircle, Calculator, Wallet, ListPlus, Trash2, 
  User, BedDouble, Tv, UploadCloud, FileCheck, CheckCircle, AlertTriangle, Info, HelpCircle, Calendar
} from "lucide-react";
import { ref, uploadBytes, getDownloadURL } from "firebase/storage"; 
import { storage } from "@/lib/firebase"; 

type AddGuestModalProps = {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: any) => Promise<boolean>; 
  isSaving: boolean;
  initialData?: any; 
};

// --- HELPER DATE ---
const toLocalYMD = (d: Date) => {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

const formatDateToInput = (date: any) => {
  if (!date) return toLocalYMD(new Date());
  if (typeof date === 'string' && date.includes('-')) return date.split('T')[0];
  if (date instanceof Date) return toLocalYMD(date);
  if (date.seconds) return toLocalYMD(new Date(date.seconds * 1000));
  return toLocalYMD(new Date());
};

// --- TYPE & STATE UNTUK TOAST ---
type ToastState = {
  show: boolean;
  message: string;
  type: "success" | "error" | "warning";
};

// INITIAL STATE
const INITIAL_FORM = {
  checkInDate: "",
  checkOutDate: "",
  guestName: "",
  roomType: "",
  channel: "Walk-in",
  voucherCode: "",
  notes: "",
  feePercentage: "" as any, 
  status: "LUNAS",
  proofUrl: "" 
};

type DailyRate = {
  date: string;
  amount: number | string;
  paidCash: number | string;
  paidTransfer: number | string;
};

// --- DATA CHANNEL (A-Z) ---
const CHANNELS = [
  { id: "Agoda", label: "Agoda", defaultFee: 18, type: "OTA" },
  { id: "Airbnb", label: "Airbnb", defaultFee: 3, type: "OTA" },
  { id: "Booking.com", label: "Booking.com", defaultFee: 17, type: "OTA" },
  { id: "Booking Engine", label: "Booking Engine", defaultFee: 0, type: "OTA" },
  { id: "Expedia", label: "Expedia", defaultFee: 18, type: "OTA" },
  { id: "MG Bedbank", label: "MG Bedbank", defaultFee: 15, type: "OTA" },
  { id: "Nexura Sales", label: "Nexura Sales", defaultFee: 15, type: "DIRECT" },
  { id: "Tiket.com", label: "Tiket.com", defaultFee: 15, type: "OTA" },
  { id: "Traveloka", label: "Traveloka", defaultFee: 15, type: "OTA" },
  { id: "Trip.com", label: "Trip.com", defaultFee: 15, type: "OTA" },
  { id: "Walk-in", label: "Walk-in", defaultFee: 0, type: "DIRECT" },
];

export default function AddGuestModal({ isOpen, onClose, onSubmit, isSaving, initialData }: AddGuestModalProps) {
  // STATE FORM
  const [formData, setFormData] = useState(INITIAL_FORM);
  const [file, setFile] = useState<File | null>(null); 
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [dailyRates, setDailyRates] = useState<DailyRate[]>([]);

  // STATE UI
  const [queue, setQueue] = useState<any[]>([]);
  const [toast, setToast] = useState<ToastState>({ show: false, message: "", type: "success" });
  
  // STATE KHUSUS UNTUK KONFIRMASI (Pengganti Alert)
  const [showUnsavedConfirm, setShowUnsavedConfirm] = useState(false);

  // CSS Helper
  const noSpinnerClass = "[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none";

  // EFFECT: Reset Data
  useEffect(() => {
    if (isOpen) {
        if (initialData) {
            setFormData({ 
                ...INITIAL_FORM, 
                ...initialData,
                checkInDate: formatDateToInput(initialData.transactionDate || new Date()),
                checkOutDate: formatDateToInput(initialData.transactionDate || new Date())
            });
            setDailyRates([{
                date: formatDateToInput(initialData.transactionDate || new Date()),
                amount: initialData.amount || "",
                paidCash: initialData.paidCash || "",
                paidTransfer: initialData.paidTransfer || ""
            }]);
            setQueue([]); 
        } else {
            const today = new Date();
            const tomorrow = new Date(today);
            tomorrow.setDate(tomorrow.getDate() + 1);
            setFormData({
                ...INITIAL_FORM,
                checkInDate: formatDateToInput(today), 
                checkOutDate: formatDateToInput(tomorrow) 
            });
            // dailyRates will be auto-generated by another effect
            setQueue([]); 
        }
        setFile(null);
        setToast({ show: false, message: "", type: "success" });
        setShowUnsavedConfirm(false);
    }
  }, [isOpen, initialData]);

  // EFFECT: Auto-generate/Update Daily Rates
  useEffect(() => {
    if (!isOpen || !formData.checkInDate) return;
    
    // Parse the YYYY-MM-DD input string directly into local Date
    const parseLocal = (ds: string) => {
        if (!ds) return new Date();
        const [y, m, d] = ds.split('-');
        return new Date(Number(y), Number(m)-1, Number(d));
    };
    
    const startDate = parseLocal(formData.checkInDate);
    let endDate = parseLocal(formData.checkOutDate || formData.checkInDate);
    
    startDate.setHours(0,0,0,0);
    endDate.setHours(0,0,0,0);
    
    let nights = Math.round((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
    
    // Di dunia perhotelan, Check-In: 20 dan Check-Out: 21 artinya 1 Malam (Malam tgl 20 saja yang dibayar)
    if (nights <= 0) nights = 1;

    // if Edit mode, force nights = 1
    if (initialData) nights = 1;

    setDailyRates(prev => {
        const newRates = [];
        for (let i = 0; i < nights; i++) {
            const currentDate = new Date(startDate);
            currentDate.setDate(currentDate.getDate() + i);
            const dateStr = formatDateToInput(currentDate);
            
            const existing = prev.find(r => r.date === dateStr);
            if (existing) {
                newRates.push(existing);
            } else {
                const defaultAmount = prev.length > 0 ? prev[0].amount : "";
                const defaultCash = prev.length > 0 ? prev[0].paidCash : "";
                const defaultTransfer = prev.length > 0 ? prev[0].paidTransfer : "";

                newRates.push({
                   date: dateStr,
                   amount: defaultAmount,
                   paidCash: defaultCash,
                   paidTransfer: defaultTransfer
                });
            }
        }
        return newRates;
    });
  }, [formData.checkInDate, formData.checkOutDate, isOpen, initialData]);

  // EFFECT: Auto Hide Toast
  useEffect(() => {
    if (toast.show) {
      const timer = setTimeout(() => setToast(prev => ({ ...prev, show: false })), 3000);
      return () => clearTimeout(timer);
    }
  }, [toast.show]);

  const showToast = (message: string, type: "success" | "error" | "warning") => {
    setToast({ show: true, message, type });
  };

  const handleChange = (field: string, value: any) => {
    let newData = { ...formData, [field]: value };
    if (field === "channel" && !initialData) {
      const ch = CHANNELS.find(c => c.id === value);
      if (ch) newData.feePercentage = ch.defaultFee === 0 ? "" : ch.defaultFee;
    }
    setFormData(newData);
  };

  const handleDailyRateChange = (index: number, field: string, value: string) => {
      setDailyRates(prev => {
          const newRates = [...prev];
          newRates[index] = { ...newRates[index], [field]: value };
          return newRates;
      });
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  // --- LOGIC PERHITUNGAN ---
  const selectedChannel = CHANNELS.find(c => c.id === formData.channel);
  const isOTA = selectedChannel?.type === "OTA";
  
  const totalGross = dailyRates.reduce((sum, rate) => sum + (Number(rate.amount) || 0), 0);
  const totalPaidCash = dailyRates.reduce((sum, rate) => sum + (Number(rate.paidCash) || 0), 0);
  const totalPaidTransfer = dailyRates.reduce((sum, rate) => sum + (Number(rate.paidTransfer) || 0), 0);
  const totalPaid = totalPaidCash + totalPaidTransfer;
  
  const feePct = parseFloat(formData.feePercentage?.toString() || "0") || 0;
  const totalFeeAmount = (totalGross * feePct) / 100;
  const totalGap = totalPaid - totalGross;
  const totalNetOwner = totalGross - totalFeeAmount;
  
  // --- HELPER: PREPARE DATA ---
  const prepareDataItem = async () => {
    if (!formData.guestName.trim()) { showToast("Nama Tamu wajib diisi!", "error"); return null; }
    
    // Check if any daily rate has amount 0
    const invalidRate = dailyRates.find(r => Number(r.amount) <= 0);
    if (invalidRate) {
        showToast(`Nominal Transaksi untuk tanggal ${invalidRate.date} tidak boleh 0`, "error"); 
        return null;
    }

    let uploadedUrl = formData.proofUrl;
    if (file) {
        setIsUploading(true);
        try {
            const filename = `${formData.guestName.replace(/\s+/g, '_')}_${Date.now()}`;
            const storageRef = ref(storage, `payment_proofs/${filename}`);
            const snapshot = await uploadBytes(storageRef, file);
            uploadedUrl = await getDownloadURL(snapshot.ref);
        } catch (error) {
            showToast("Gagal upload gambar, periksa koneksi.", "error");
            setIsUploading(false);
            return null;
        } finally {
            setIsUploading(false);
        }
    }

    const items = [];
    
    for (let i = 0; i < dailyRates.length; i++) {
        const rate = dailyRates[i];
        
        const gross = Number(rate.amount) || 0;
        const feeAmount = (gross * feePct) / 100;
        const totalPaid = (Number(rate.paidCash) || 0) + (Number(rate.paidTransfer) || 0);
        const gap = totalPaid - gross;
        const netOwner = gross - feeAmount;

        let statusLabel = "LUNAS";
        let statusColor = "bg-emerald-100 text-emerald-700";
        if (isOTA) {
            statusLabel = gap === 0 ? "MATCHED" : "GAP DETECTED";
            statusColor = gap === 0 ? "bg-blue-100 text-blue-700" : "bg-orange-100 text-orange-700";
        } else {
            const isPaidOff = totalPaid >= gross;
            statusLabel = isPaidOff ? "LUNAS" : "BELUM LUNAS";
            statusColor = isPaidOff ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700";
        }

        items.push({
            ...formData,
            transactionDate: rate.date, 
            amount: gross, 
            paidCash: Number(rate.paidCash) || 0,
            paidTransfer: Number(rate.paidTransfer) || 0,
            feePercentage: feePct,
            status: statusLabel,
            proofUrl: uploadedUrl,
            _isOTA: isOTA,
            _gap: gap,
            _netOwner: netOwner
        });
    }

    return items;
  };

  // --- ADD TO QUEUE ---
  const handleAddToQueue = async () => {
    const newItems = await prepareDataItem();
    if (newItems && newItems.length > 0) {
        setQueue([...queue, ...newItems]);
        // Reset form tapi pertahankan tanggal
        setFormData({ ...INITIAL_FORM, checkInDate: formData.checkInDate, checkOutDate: formData.checkOutDate }); 
        // Reset rincian dailyRates agar form dianggap sudah tidak dirty
        setDailyRates(prev => prev.map(r => ({ ...r, amount: "", paidCash: "", paidTransfer: "" })));
        setFile(null);
        showToast(`${newItems.length} hari berhasil ditambahkan ke antrian`, "success");
    }
  };

  const handleRemoveFromQueue = (index: number) => {
    const newQueue = [...queue];
    newQueue.splice(index, 1);
    setQueue(newQueue);
    showToast("Item dihapus dari antrian", "warning");
  };

  // --- CORE: EXECUTE SAVE (Logic Penyimpanan Fisik) ---
  const executeBatchSave = async (finalQueue: any[]) => {
      // Logic Simpan (API Call)
      let successCount = 0;
      
      // Jika Mode Edit
      if (initialData && finalQueue.length === 1) {
          const { _isOTA, _gap, _netOwner, ...dbData } = finalQueue[0];
          const success = await onSubmit(dbData);
          if (success) {
              showToast("Data berhasil diperbarui!", "success");
              setTimeout(onClose, 1000);
          }
          return;
      }

      // Jika Mode Batch
      for (const item of finalQueue) {
          const { _isOTA, _gap, _netOwner, ...dbData } = item; 
          const success = await onSubmit(dbData);
          if (success) successCount++;
      }

      if (successCount === finalQueue.length) {
          showToast(`SUKSES! ${successCount} data berhasil disimpan.`, "success");
          setQueue([]);
          const today = new Date();
          const tomorrow = new Date(today);
          tomorrow.setDate(tomorrow.getDate() + 1);
          setFormData({ ...INITIAL_FORM, checkInDate: formatDateToInput(today), checkOutDate: formatDateToInput(tomorrow) });
          setShowUnsavedConfirm(false); // Tutup modal confirm jika terbuka
          setTimeout(onClose, 1500); 
      } else {
          showToast(`Hanya ${successCount} dari ${finalQueue.length} tersimpan.`, "warning");
          setShowUnsavedConfirm(false);
      }
  };

  // --- TRIGGER: KLIK TOMBOL PROSES ---
  const handleProcessClick = async () => {
    // 1. Cek apakah Form sedang terisi (Dirty Check)
    const isFormDirty = formData.guestName.trim() !== "" || dailyRates.some(r => Number(r.amount) > 0);
    
    // Jika ada data 'nyangkut' di form dan bukan mode edit
    if (isFormDirty && !initialData) {
        setShowUnsavedConfirm(true); // TAMPILKAN CUSTOM MODAL, BUKAN ALERT
        return;
    }

    if (queue.length === 0 && !initialData) {
        showToast("List kosong! Isi data terlebih dahulu.", "error");
        return;
    }

    // Jika mode edit, proses data form saat ini
    if (initialData) {
        const items = await prepareDataItem();
        if (items && items.length > 0) {
            executeBatchSave(items);
        }
        return;
    }

    // Jika bersih, langsung simpan queue
    executeBatchSave(queue);
  };

  // --- ACTION: USER MEMILIH "INCLUDE & SAVE" DI CUSTOM MODAL ---
  const handleConfirmIncludeAndSave = async () => {
    const currentItems = await prepareDataItem(); // Ambil data form saat ini
    if (!currentItems || currentItems.length === 0) {
        // Jika validasi gagal (misal nama kosong), tutup modal confirm biar user benerin dulu
        setShowUnsavedConfirm(false); 
        return; 
    }
    // Gabungkan queue yang ada + item yang baru diketik
    const finalQueue = [...queue, ...currentItems];
    executeBatchSave(finalQueue);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in zoom-in-95 duration-200">
      
      {/* 1. TOAST NOTIFICATION */}
      {toast.show && (
          <div className={`absolute top-6 left-1/2 transform -translate-x-1/2 z-[80] flex items-center gap-3 px-6 py-4 rounded-2xl shadow-2xl animate-in slide-in-from-top-4 duration-300 ${
              toast.type === 'success' ? 'bg-emerald-600 text-white' : 
              toast.type === 'error' ? 'bg-red-500 text-white' : 'bg-amber-500 text-white'
          }`}>
              {toast.type === 'success' && <CheckCircle size={24} className="text-white/90" />}
              {toast.type === 'error' && <AlertTriangle size={24} className="text-white/90" />}
              {toast.type === 'warning' && <Info size={24} className="text-white/90" />}
              <div>
                  <h4 className="font-bold text-sm">{toast.type === 'success' ? 'Berhasil' : toast.type === 'error' ? 'Gagal' : 'Perhatian'}</h4>
                  <p className="text-xs text-white/90 font-medium">{toast.message}</p>
              </div>
          </div>
      )}

      {/* 2. CUSTOM CONFIRMATION MODAL (PENGGANTI ALERT) */}
      {showUnsavedConfirm && (
          <div className="absolute inset-0 z-[70] flex items-center justify-center bg-black/40 backdrop-blur-sm animate-in fade-in duration-200">
             <div className="bg-white rounded-2xl shadow-2xl p-6 max-w-sm w-full mx-4 animate-in zoom-in-95 duration-200 border border-gray-100">
                <div className="flex flex-col items-center text-center space-y-4">
                    <div className="w-16 h-16 bg-amber-100 rounded-full flex items-center justify-center text-amber-500 mb-2">
                        <HelpCircle size={32} />
                    </div>
                    <div>
                        <h4 className="text-lg font-bold text-gray-800">Data Belum Masuk Antrian</h4>
                        <p className="text-sm text-gray-500 mt-2">
                           Anda masih memiliki data di formulir yang belum ditambahkan. Apakah Anda ingin menyertakan data ini?
                        </p>
                    </div>
                    <div className="grid grid-cols-2 gap-3 w-full mt-2">
                        <button 
                            onClick={() => setShowUnsavedConfirm(false)} 
                            className="w-full py-2.5 rounded-xl border border-gray-200 font-bold text-gray-600 hover:bg-gray-50 transition-colors"
                        >
                            Batal / Edit
                        </button>
                        <button 
                            onClick={handleConfirmIncludeAndSave} 
                            disabled={isSaving}
                            className="w-full py-2.5 rounded-xl bg-blue-600 text-white font-bold hover:bg-blue-700 shadow-lg shadow-blue-600/20 transition-colors"
                        >
                           {isSaving ? "Memproses..." : "Ya, Sertakan"}
                        </button>
                    </div>
                </div>
             </div>
          </div>
      )}

      {/* 3. MAIN MODAL CONTAINER */}
      <div className="bg-white w-full max-w-6xl rounded-3xl shadow-2xl flex flex-col max-h-[95vh] overflow-hidden relative z-50">
        
        {/* HEADER */}
        <div className="flex justify-between items-center px-8 py-4 border-b border-gray-100 bg-white">
          <div className="flex items-center gap-3">
             <h3 className="text-xl font-bold text-gray-900">{initialData ? "Edit Transaksi" : "Input Massal Transaksi"}</h3>
             <span className="px-3 py-1 bg-gray-100 text-gray-600 text-xs font-bold rounded-full border border-gray-200">
                {queue.length} Item di Antrian
             </span>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full transition-colors"><X size={24} className="text-gray-400"/></button>
        </div>

        {/* CONTENT */}
        <div className="flex-1 overflow-y-auto bg-gray-50/50">
            <div className="grid grid-cols-1 lg:grid-cols-3 h-full min-h-[500px]">
                
                {/* --- KOLOM KIRI: INPUT FORM --- */}
                <div className="lg:col-span-2 p-8 space-y-6 bg-white">
                    <div className="flex items-center justify-between">
                        <h4 className="font-bold text-gray-700 flex items-center gap-2"><ListPlus size={18}/> Form Input</h4>
                        
                        {/* --- NEW: CHECK IN & CHECK OUT DATES --- */}
                        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-2">
                             <div className="flex items-center gap-2 bg-blue-50 px-3 py-1.5 rounded-lg border border-blue-100 w-full sm:w-auto">
                                 <Calendar size={14} className="text-blue-600"/>
                                 <span className="text-xs font-bold text-blue-700">IN</span>
                                 <input 
                                    type="date" 
                                    className="bg-transparent text-xs font-bold text-blue-700 outline-none uppercase cursor-pointer w-full"
                                    value={formData.checkInDate}
                                    onChange={(e) => handleChange("checkInDate", e.target.value)}
                                 />
                             </div>
                             <div className="flex items-center gap-2 bg-orange-50 px-3 py-1.5 rounded-lg border border-orange-100 w-full sm:w-auto">
                                 <Calendar size={14} className="text-orange-600"/>
                                 <span className="text-xs font-bold text-orange-700">OUT</span>
                                 <input 
                                    type="date" 
                                    className="bg-transparent text-xs font-bold text-orange-700 outline-none uppercase cursor-pointer w-full"
                                    value={formData.checkOutDate}
                                    onChange={(e) => handleChange("checkOutDate", e.target.value)}
                                 />
                             </div>
                        </div>

                    </div>

                    {/* Guest Info */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase">Nama Tamu *</label>
                            <input className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl font-bold text-gray-800 outline-none focus:ring-2 focus:ring-blue-500" placeholder="Nama Lengkap..." value={formData.guestName} onChange={(e) => handleChange("guestName", e.target.value)} />
                        </div>
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase">Kamar / No</label>
                            <input className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl font-medium" placeholder="Cth: 101" value={formData.roomType} onChange={(e) => handleChange("roomType", e.target.value)} />
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                        <div className="space-y-1.5 md:col-span-1">
                            <label className="text-xs font-bold text-gray-500 uppercase">Channel Source</label>
                            <select className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl font-medium cursor-pointer" value={formData.channel} onChange={(e) => handleChange("channel", e.target.value)}>
                                {CHANNELS.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                            </select>
                        </div>
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase">Kode Voucher</label>
                            <input className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl font-mono uppercase text-sm" placeholder="OPTIONAL" value={formData.voucherCode} onChange={(e) => handleChange("voucherCode", e.target.value)} />
                        </div>
                         <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase">Fee Mgmt (%)</label>
                            <input 
                                type="number" 
                                placeholder="0"
                                className={`w-full p-3 bg-white border border-gray-200 rounded-xl font-bold text-center ${noSpinnerClass}`} 
                                value={formData.feePercentage} 
                                onChange={(e) => handleChange("feePercentage", e.target.value)} 
                                onWheel={(e) => (e.target as HTMLInputElement).blur()}
                            />
                        </div>
                    </div>

                    {/* FINANCIAL INPUT */}
                    <div className={`p-6 rounded-2xl border space-y-5 ${isOTA ? 'bg-orange-50 border-orange-100' : 'bg-blue-50 border-blue-100'}`}>
                        <label className={`text-xs font-bold uppercase flex items-center gap-2 ${isOTA ? 'text-orange-700' : 'text-blue-600'}`}>
                            <Calculator size={14}/> {isOTA ? "Rincian Booking (Ezee CM)" : "Rincian Tagihan Tamu"}
                        </label>
                        
                        <div className="space-y-4 max-h-[350px] overflow-y-auto pr-2 pb-2">
                           {dailyRates.map((rate, idx) => (
                               <div key={idx} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                                  {/* Header Tanggal */}
                                  <div className="bg-gray-50 border-b border-gray-100 px-4 py-2.5 flex justify-between items-center">
                                      <span className="text-xs font-bold text-gray-700 font-mono flex items-center gap-1.5"><Calendar size={13} className="text-blue-500" />{rate.date}</span>
                                      <span className="text-[10px] font-extrabold text-gray-400 uppercase tracking-wider bg-white px-2 py-0.5 rounded-full border border-gray-200 shadow-sm">Malam ke-{idx + 1}</span>
                                  </div>
                                  
                                  <div className="p-4 space-y-4">
                                     <div className="relative">
                                        <span className="absolute left-4 top-3 text-gray-400 font-bold text-sm">Rp</span>
                                        <input 
                                            type="number" 
                                            placeholder="Harga Per Hari"
                                            className={`w-full pl-12 pr-4 py-2.5 bg-gray-50 border rounded-xl font-bold text-gray-900 outline-none shadow-sm transition-all focus:bg-white ${isOTA ? 'border-orange-300 focus:border-orange-500 focus:ring-4 focus:ring-orange-100' : 'border-blue-300 focus:border-blue-500 focus:ring-4 focus:ring-blue-100'} ${noSpinnerClass}`} 
                                            value={rate.amount} 
                                            onChange={(e) => handleDailyRateChange(idx, "amount", e.target.value)} 
                                            onWheel={(e) => (e.target as HTMLInputElement).blur()}
                                        />
                                     </div>
                                     <div className="grid grid-cols-2 gap-3">
                                         <div className="space-y-1.5">
                                             <label className="text-[10px] font-extrabold text-emerald-600 uppercase flex justify-between">
                                                 <span>PAY Hotel (Cash)</span>
                                             </label>
                                             <input 
                                                 type="number" 
                                                 placeholder="0"
                                                 className={`w-full p-2.5 bg-gray-50 border border-emerald-200 rounded-xl font-bold text-emerald-700 outline-none focus:bg-white focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 transition-all ${noSpinnerClass} text-sm`} 
                                                 value={rate.paidCash} 
                                                 onChange={(e) => handleDailyRateChange(idx, "paidCash", e.target.value)} 
                                                 onWheel={(e) => (e.target as HTMLInputElement).blur()}
                                             />
                                         </div>
                                         <div className="space-y-1.5">
                                             <label className="text-[10px] font-extrabold text-indigo-600 uppercase flex justify-between">
                                                 <span>{isOTA ? "Net Extranet" : "PAY NEXURA"}</span>
                                             </label>
                                             <input 
                                                 type="number" 
                                                 placeholder="0"
                                                 className={`w-full p-2.5 bg-gray-50 border border-indigo-200 rounded-xl font-bold text-indigo-700 outline-none focus:bg-white focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100 transition-all ${noSpinnerClass} text-sm`} 
                                                 value={rate.paidTransfer} 
                                                 onChange={(e) => handleDailyRateChange(idx, "paidTransfer", e.target.value)} 
                                                 onWheel={(e) => (e.target as HTMLInputElement).blur()}
                                             />
                                         </div>
                                     </div>
                                  </div>
                               </div>
                           ))}
                        </div>
                    </div>

                    {/* UPLOAD & NOTES */}
                    <div className="grid grid-cols-2 gap-5">
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase flex justify-between">
                                <span>Bukti Pembayaran</span>
                                {file && <span className="text-emerald-600 flex items-center gap-1"><FileCheck size={12}/> Ready</span>}
                            </label>
                            <div className={`border-2 border-dashed rounded-xl p-3 flex flex-col items-center justify-center cursor-pointer h-[100px] ${file ? 'border-emerald-300 bg-emerald-50' : 'border-gray-300 hover:bg-gray-50'}`} onClick={() => fileInputRef.current?.click()}>
                                <input type="file" ref={fileInputRef} className="hidden" accept="image/*,application/pdf" onChange={handleFileChange} />
                                {file ? <p className="text-xs font-bold text-emerald-700 text-center truncate w-full">{file.name}</p> : <div className="text-center text-gray-400"><UploadCloud size={20} className="mx-auto mb-1"/><span className="text-[10px]">Upload Bukti</span></div>}
                            </div>
                        </div>
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-gray-500 uppercase">Catatan</label>
                            <textarea className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl text-sm resize-none h-[100px]" value={formData.notes} onChange={(e) => handleChange("notes", e.target.value)} />
                        </div>
                    </div>

                    {!initialData && (
                        <button onClick={handleAddToQueue} disabled={isUploading} className="w-full py-3 bg-gray-800 text-white font-bold rounded-xl hover:bg-black transition-all flex items-center justify-center gap-2 active:scale-95">
                           {isUploading ? <UploadCloud className="animate-bounce" size={18}/> : <PlusCircle size={18}/>} 
                           Tambahkan ke List Antrian
                        </button>
                    )}
                </div>

                {/* --- KOLOM KANAN: REVIEW LENGKAP --- */}
                <div className="lg:col-span-1 bg-slate-50 border-l border-gray-100 p-8 flex flex-col h-full overflow-hidden">
                    <h4 className="text-sm font-extrabold text-slate-400 uppercase tracking-widest flex items-center gap-2 mb-6"><Wallet size={16}/> Review Transaksi</h4>
                    
                    <div className="flex-1 overflow-y-auto space-y-4 pr-1">
                        {/* 1. DETAIL TAMU */}
                        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm space-y-3">
                            <p className="text-xs font-bold text-gray-400 uppercase border-b border-gray-100 pb-2 mb-2 flex justify-between">
                                <span>Detail Tamu</span>
                                <span className="text-blue-600">{formData.checkInDate} to {formData.checkOutDate}</span>
                            </p>
                            <div className="flex items-start gap-3">
                                <div className="w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center text-blue-600 shrink-0"><User size={18}/></div>
                                <div>
                                    <div className="font-bold text-gray-900 leading-tight">{formData.guestName || "-"}</div>
                                    <div className="text-xs text-gray-500 mt-1 flex items-center gap-2">
                                        <span className="flex items-center gap-1"><BedDouble size={10}/> {formData.roomType || "No Room"}</span>
                                        <span className="flex items-center gap-1"><Tv size={10}/> {formData.channel}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* 2. DETAIL KEUANGAN */}
                        <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm space-y-3">
                             <p className="text-xs font-bold text-gray-400 uppercase border-b border-gray-100 pb-2 mb-2 flex justify-between">
                                  <span>Kalkulasi Total</span>
                                  <span className="text-indigo-600 px-2 py-0.5 bg-indigo-50 rounded-full text-[10px]">{dailyRates.length} Malam</span>
                             </p>
                             <div className="flex justify-between text-sm"><span className="text-gray-500">{isOTA ? "Total Ezee CM" : "Total Tagihan"}</span><span className="font-bold">{new Intl.NumberFormat("id-ID").format(totalGross)}</span></div>
                             <div className="flex justify-between text-sm"><span className="text-gray-500">Total Fee ({formData.feePercentage || 0}%)</span><span className="font-bold text-red-500">-{new Intl.NumberFormat("id-ID").format(totalFeeAmount)}</span></div>
                             <div className="border-t border-dashed border-gray-200 my-1"></div>
                             <div className="flex justify-between text-sm"><span className="text-gray-500 font-bold">Total Net Owner</span><span className="font-bold text-emerald-600">{new Intl.NumberFormat("id-ID").format(totalNetOwner)}</span></div>
                        </div>

                        {/* 3. PAYMENT STATUS */}
                        <div className={`bg-white p-4 rounded-xl border shadow-sm space-y-3 ${isOTA ? 'border-orange-100' : 'border-gray-200'}`}>
                            <div className={`w-full py-2 rounded text-center font-bold text-[10px] tracking-wide mb-2 ${isOTA ? (totalGap === 0 ? "bg-blue-100 text-blue-700" : "bg-orange-100 text-orange-700") : (totalPaid >= totalGross ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700")}`}>STATUS BERDASARKAN TOTAL</div>
                            <div className="flex justify-between text-xs"><span className="text-emerald-600 font-bold">Total PAY Hotel</span><span className="font-mono">{new Intl.NumberFormat("id-ID").format(totalPaidCash)}</span></div>
                            <div className="flex justify-between text-xs"><span className="text-indigo-600 font-bold">Total PAY Nexura</span><span className="font-mono">{new Intl.NumberFormat("id-ID").format(totalPaidTransfer)}</span></div>
                            <div className="border-t border-gray-100 my-2"></div>
                            <div className="flex justify-between text-sm font-bold">
                                <span className={totalGap < 0 ? "text-red-500" : "text-gray-400"}>{totalGap < 0 ? (isOTA ? "GAP / Selisih" : "Kurang") : "Matched Semua"}</span>
                                <span className={totalGap < 0 ? "text-red-600" : "text-gray-400"}>{new Intl.NumberFormat("id-ID").format(Math.abs(totalGap))}</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        {/* --- FOOTER --- */}
        {!initialData && (
            <div className="border-t border-gray-200 bg-white p-6">
                <div className="flex flex-col md:flex-row gap-6 h-full">
                    <div className="flex-1 bg-gray-50 rounded-xl border border-gray-200 overflow-hidden flex flex-col h-[150px]">
                        <div className="bg-gray-100 px-4 py-2 border-b border-gray-200 flex justify-between">
                            <span className="text-xs font-bold text-gray-500 uppercase">List Antrian ({queue.length})</span>
                            <span className="text-[10px] text-gray-400 italic">Review sebelum simpan</span>
                        </div>
                        <div className="overflow-y-auto p-0">
                            <table className="w-full text-left text-xs">
                                <thead className="text-gray-400 font-medium bg-white sticky top-0">
                                    <tr>
                                        <th className="p-2">Tgl</th>
                                        <th className="p-2">Nama</th>
                                        <th className="p-2 text-right">Gross</th>
                                        <th className="p-2 text-right">Net Owner</th>
                                        <th className="p-2 text-center">Aksi</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100">
                                    {queue.length === 0 ? (
                                        <tr><td colSpan={6} className="p-8 text-center text-gray-400 italic">Belum ada data di antrian. Input data diatas lalu klik "Tambahkan ke List".</td></tr>
                                    ) : (
                                        queue.map((item, idx) => (
                                            <tr key={idx} className="bg-white hover:bg-blue-50">
                                                <td className="p-2 font-mono text-gray-500">{item.transactionDate}</td>
                                                <td className="p-2 font-bold">{item.guestName}</td>
                                                <td className="p-2 text-right">{new Intl.NumberFormat("id-ID").format(item.amount)}</td>
                                                <td className="p-2 text-right text-emerald-600">{new Intl.NumberFormat("id-ID").format(item._netOwner)}</td>
                                                <td className="p-2 text-center"><button onClick={() => handleRemoveFromQueue(idx)} className="text-red-400 hover:text-red-600"><Trash2 size={14}/></button></td>
                                            </tr>
                                        ))
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div className="w-full md:w-[250px] flex flex-col justify-end gap-2">
                        <div className="text-right text-xs text-gray-400 mb-1">
                            Total Item: <span className="font-bold text-gray-800">{queue.length}</span>
                        </div>
                        <button 
                            onClick={handleProcessClick}
                            disabled={isSaving || isUploading}
                            className={`w-full py-4 text-base font-bold text-white rounded-xl shadow-lg flex items-center justify-center gap-2 active:scale-95 transition-all ${isSaving ? 'bg-gray-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700 shadow-blue-600/20'}`}
                        >
                            <Save size={20}/> {isSaving ? "Memproses..." : "PROSES SEMUA DATA"}
                        </button>
                    </div>
                </div>
            </div>
        )}

        {initialData && (
             <div className="px-8 py-5 bg-gray-50 border-t border-gray-100 flex justify-end">
                <button 
                    onClick={handleProcessClick}
                    disabled={isSaving || isUploading}
                    className="px-8 py-3 text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 rounded-xl shadow-lg flex items-center justify-center gap-2"
                >
                    <Save size={18}/> Update Perubahan
                </button>
             </div>
        )}

      </div>
    </div>
  );
}